#! /bin/bash
echo "Informe o numero da loja."
read LOJA
echo "Informe a data do moviento do arquivo no modelo aaaammdd:"
read DATA
echo "Informe a quantidade de arquivos:"
read QTARQ
dia=`julian` # $DATA`
case $QTARQ in 
	1) echo "Informe o nome do arquivo:"
	read ARQ
	cd /home2/makro/st_rcv/str_000$LOJA
	tail -2 $ARQ$dia
	;;
	2) echo "Informe o primeiro arquivo:"
	read ARQ1
	   echo "Informe o segundo arquivo:"
	read ARQ2
	cd /home2/makro/st_rcv/str_000$LOJA
	tail -2 $ARQ1$dia
	
	tail -2 $ARQ2$dia
	;;
	*) echo "Quantidade invalida"
	;;
esac 
