SET ECHO ON
SET HEADING OFF
SET VERIFY OFF
SET PAGESIZE 0
SET LINESIZE 600
SET FEEDBACK ON
alter session set NLS_NUMERIC_CHARACTERS = ',.';
PL/SQL 'EXECUTANDO LOJA:', STORE_NO from STORE;
spool OFF
exit


