$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARECOM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTCAE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTEND_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTERRO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTIVA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTREP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTSEL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTTEC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTVED_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACBATTOT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACBLQPAL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCABEND_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCABTEC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCEPCID_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCEPCID_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCEPRUA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCHQRET_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLICMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIDSP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLINFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIPRI_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIRES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLISEC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLISEL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIVEM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCNVDES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDESREP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDETEND_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDIGNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACEGALOJ_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACENDALT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACETQTMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACGRPDES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACINVGER_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACINVGER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACINVGER_DT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACINVGER_TT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACLINTEC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACMGRCOM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACMODEND_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACOCRBAR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACPRVFUT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACRESECF_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACRESECP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACROTBUS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSBACOM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSGRCOM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSMGCOM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTABAUX_CASH_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTABUFE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTAXICM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTIPPAL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTIPRUA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/AGR_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARARTSUG_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARCESKIT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARSEQCOD_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARTICLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARTICLE_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_GRP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_GRP_STAT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_SCALE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_SCALE_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/BARCODE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/BAR_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CALENDAR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CARD_TYPE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEAUTAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CECABNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEDETNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEDEVDDB_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEHSTIMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CENATOPE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CETABEMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CETIPAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLATIVDE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCARCRD_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCLILOG_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCOMMES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCONFON_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCURABC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLGRPABC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLGRPVEN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLHISCTA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLHISOUR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLLOGALT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLOUTLOJ_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLPARJMO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLPESJMO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLROTJMO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLSELCTA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLSELJMO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLTOTCTA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLVENGRP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/COMPBAR_TEMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/COMPCAD_TEMP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTALIECF_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTATVMAP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTCABMAP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTCADECF_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTDETMAP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTLOGMAP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTNFSUBS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_AGM_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_AREA_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_BLOCKING_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_GRP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_PASS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SALES_PROFIT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SGRP_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_TYPE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DEPT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DISTRICT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DIS_MSALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DUMMY_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EMPL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ERRO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ETGRPDIA_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EXT_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EX_LATER_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/FOLDER_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/GENVAR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/GENVAR_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_LINE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_VAT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INV_PAYM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_LINE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_PAYMENT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_VAT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVCONFAC_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVFACVAO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVPAGVAO_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVPARFOR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVVERCAB_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVVERDET_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/LIST_TEXT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/LOG_PRINT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MESSAGES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMARTPRM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMARTVEN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMART_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MM_ARTICLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MM_CALENDAR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/NET_NODES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDERS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_LINE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_STATUS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_TYPE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PAYMENT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PAYM_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTMOV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTNEW_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTTRN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCCABNEW_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCCABTRN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCDIASUG_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCMSGTRN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCPEDCTL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PLAN_TABLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PLU_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPARTPES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPARTTRN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCABPES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCABTRN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCONPES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PROP_ORDER_LINE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_NEW_ARTICLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_NIGHTRUN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STALC010_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS040_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS060_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS061_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR050_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR060_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR070_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/REGION_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/REP_MSALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RLINFCTL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTCAT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTMOV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTROM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCABAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCABNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCHKBAR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCTRAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMDETAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMFORAJU_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMSLPMOV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMVALNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RUN_SEQUENCE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SCALE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHADOW_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHARTPRV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_LIFT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_OFF_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_ON_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_PAYMENT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_VAT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHPROART_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHPROCAB_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_ARTICLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_BARCODE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_TB_ARTDEL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SKNOTPDV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/STORE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/STORE_LAYOUT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPLIER_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_ADDR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_STATUS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_TYPE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYAPLAUT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYAPLLOG_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYCMPPDV_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYCNTROT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYMSGERR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYPARCTL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYPARSEL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYSOLREL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYTIPAUT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYUSRAUT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TAX_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TAX_QUEUE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_ARTICLE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_BARCODE_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_CUST_AREA_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_CUST_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_EARLY_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_FOREIGN_SALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_STOCK_CORR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_SUPPLIER_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_SUPPL_ADDR_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TICKETS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TILL_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TIME_VISIT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TR_PRINT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TVROMCAB_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TVROMDET_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TYPE_MSALES_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TYPE_SALES_PROFIT_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VECTLNFS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VECTRSAN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VEICMDIF_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VENFSCAN_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/XREAD_POS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/XREAD_POS_PAYM_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ZREAD_POS_CI.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ZREAD_POS_PAYM_CI.sql
