$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARECOM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTCAE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTEND_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTERRO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTIVA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTREP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTSEL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTTEC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACARTVED_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACBATTOT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACBLQPAL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCABEND_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCABTEC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCEPCID_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCEPRUA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCHQRET_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLICMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIDSP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIEXT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLINFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIPRI_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIRES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLISEC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLISEL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCLIVEM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACCNVDES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDESREP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDETEND_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACDIGNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACEGALOJ_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACENDALT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACETQTMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACGRPDES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACINVGER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACLINTEC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACMGRCOM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACMODEND_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACOCRBAR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACPRVFUT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACRESECF_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACRESECP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACROTBUS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSBACOM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSGRCOM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACSMGCOM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTABAUX_CASH_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTABUFE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTAXICM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTIPPAL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ACTIPRUA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/AGR_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARARTSUG_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARCESKIT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARSEQCOD_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARTICLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ARTICLE_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_GRP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_GRP_STAT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_SCALE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ART_SCALE_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/BARCODE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/BAR_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CALENDAR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CARD_TYPE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEAUTAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CECABNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEDETNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEDEVDDB_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CEHSTIMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CENATOPE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CETABEMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CETIPAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLATIVDE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCARCRD_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCLILOG_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCOMMES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCONFON_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLCURABC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLGRPABC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLGRPVEN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLHISCTA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLHISOUR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLLOGALT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLOUTLOJ_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLPARJMO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLPESJMO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLROTJMO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLSELCTA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLSELJMO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLTOTCTA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CLVENGRP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/COMPBAR_TEMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/COMPCAD_TEMP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTALIECF_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTATVMAP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTCABMAP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTCADECF_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTDETMAP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTLOGMAP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CTNFSUBS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_AGM_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_AREA_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_BLOCKING_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_GRP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_PASS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SALES_PROFIT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_SGRP_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/CUST_TYPE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DEPT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DISTRICT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DIS_MSALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/DUMMY_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EMPL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ERRO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ETGRPDIA_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EXT_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/EX_LATER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/FOLDER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/GENVAR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/GENVAR_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_LINE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INVOICE_VAT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/HIST_INV_PAYM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_LINE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_PAYMENT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/INVOICE_VAT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVCONFAC_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVFACVAO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVPAGVAO_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVPARFOR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVVERCAB_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/IVVERDET_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/LIST_TEXT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/LOG_PRINT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMARTPRM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMARTVEN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MMART_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MM_ARTICLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/MM_CALENDAR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/NET_NODES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDERS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_LINE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_STATUS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ORDER_TYPE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PAYMENT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PAYM_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTMOV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTNEW_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCARTTRN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCCABNEW_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCCABTRN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCDIASUG_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCMSGTRN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PCPEDCTL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PLAN_TABLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PLU_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPARTPES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPARTTRN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCABPES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCABTRN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PPCONPES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/PROP_ORDER_LINE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_NEW_ARTICLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_NIGHTRUN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STALC010_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS040_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS060_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STCUS061_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR050_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR060_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/P_STGOR070_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/REGION_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/REP_MSALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RLINFCTL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTCAT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTMOV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMARTROM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCABAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCABNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCHKBAR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMCTRAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMDETAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMFORAJU_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMSLPMOV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RMVALNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/RUN_SEQUENCE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SCALE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHADOW_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHARTPRV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_LIFT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_OFF_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_ON_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_PAYMENT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHIFT_VAT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHPROART_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SHPROCAB_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_ARTICLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_BARCODE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SH_TB_ARTDEL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SKNOTPDV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/STORE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/STORE_LAYOUT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPLIER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_ADDR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_STATUS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SUPPL_TYPE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SWREORG1_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYAPLAUT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYAPLLOG_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYCMPPDV_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYCNTROT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYMSGERR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYPARCTL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYPARSEL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYSOLREL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYTIPAUT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/SYUSRAUT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TAX_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TAX_QUEUE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_ARTICLE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_BARCODE_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_CUST_AREA_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_CUST_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_EARLY_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_FOREIGN_SALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_STOCK_CORR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_SUPPLIER_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TB_SUPPL_ADDR_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TICKETS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TILL_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TIME_VISIT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TR_PRINT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TVROMCAB_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TVROMDET_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TYPE_MSALES_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/TYPE_SALES_PROFIT_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VECTLNFS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VECTRSAN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VEICMDIF_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/VENFSCAN_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/XREAD_POS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/XREAD_POS_PAYM_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ZREAD_POS_CT.sql
$ORACLE_HOME/bin/sqlplus -s ops\$storep/ops\$storep @/home/reorg/ZREAD_POS_PAYM_CT.sql

